---
  - hosts: all
    become: yes

    vars:
      goss_tests:
        - test_apache.yml

    pre_tasks:
      - name: yum update
        yum:
          name: '*'
          state: latest

    roles:
      - role: mcorbin.goss-module

    tasks:
      - name: install yum repos
        yum:
          name: "{{ item }}"
          state: latest
        with_items:
          - httpd
          - mod_ssl
          - firewalld

      - name: start httpd
        systemd:
          name: httpd
          state: started
          enabled: yes

      - name: forward http traffic to https
        lineinfile:
          path: /etc/httpd/conf/httpd.conf
          insertafter: '^Listen 80'
          line: "{{ item }}"
        with_items:
          - </VirtualHost>
          -   Redirect "/" "https://ADDRPLACEHOLDER"
          -   ServerName srechallenge
          - <VirtualHost *:80>

      - name: copy html to server
        copy:
          src: "{{ playbook_dir }}/files/index.html"
          dest: /var/www/html/index.html
          mode: 0744

      - name: open ports
        firewalld:
          port: "{{ item }}/tcp"
          permanent: yes
          state: enabled
        with_items:
          - 22
          - 80
          - 443

    post_tasks:
      - name: create goss directory
        file:
          path: /opt/goss
          state: directory
          mode: 0755

      - name: copy goss tests
        copy:
          src: "{{ playbook_dir }}/files/goss/{{ item }}"
          dest: "/opt/goss/{{ item }}"
        with_items: "{{ goss_tests }}"

      - name: run goss tests
        goss:
          path: "/opt/goss/{{ item }}"
          format: documentation
        with_items: "{{ goss_tests }}"
