---
service:
  httpd:
    running: true
    enabled: true
  
  firewalld:
    running: true
    enabled: true

file:
  /var/www/html/index.html:
    exists: true
    mode: "0744"
    contains:
      - "Hello World!"
  
  /etc/httpd/conf/httpd.conf:
    exists: true
    contains:
      - 'Redirect "/" "https://ADDRPLACEHOLDER"'

http:
  http://localhost:
    status: 200
    body:
      - "Hello World!"
